#!/usr/bin/env bash
# Apply chronomoto.conf values to split-view config.js and Chromium extension.
# Called by setup.sh — GPL-3.0-or-later

set -euo pipefail

INSTALL_DIR="${1:?INSTALL_DIR required}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="${CONFIG_FILE:-$SCRIPT_DIR/chronomoto.conf}"

if [[ -f "$CONFIG_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$CONFIG_FILE"
fi

HIGHLIGHT_NO="${HIGHLIGHT_NO:-}"
TOP_URL="${TOP_URL:-https://live.chronomoto.com/mx/}"
BOTTOM_URL="${BOTTOM_URL:-https://live.chronomoto.com/archive}"
ARCHIVE_TITLE="${ARCHIVE_TITLE:-ARCHIVE}"
DEFAULT_SPLIT="${DEFAULT_SPLIT:-60}"
SPLIT_CONFIG="${INSTALL_DIR}/split-view/config.js"
EXT_OUT="${SCRIPT_DIR}/extension-built"
EXT_TEMPLATE="${SCRIPT_DIR}/extension-template"

log() { echo "==> [apply-config] $*"; }

# Escape single quotes for JS strings
js_str() { printf "%s" "$1" | sed "s/'/\\\\'/g"; }

log "Writing split-view config.js"
cat > "$SPLIT_CONFIG" << EOF
// Generated by raspberry-pi/apply-config.sh — edit chronomoto.conf and re-run setup.sh
window.CHRONOMOTO_SPLIT_CONFIG = {
  topUrl: '$(js_str "$TOP_URL")',
  bottomUrl: '$(js_str "$BOTTOM_URL")',
  archiveTitle: '$(js_str "$ARCHIVE_TITLE")',
  defaultSplit: ${DEFAULT_SPLIT},
};
EOF

if [[ -n "$HIGHLIGHT_NO" ]]; then
  log "Building highlight extension for rider No. ${HIGHLIGHT_NO}"
  rm -rf "$EXT_OUT"
  mkdir -p "$EXT_OUT"
  cp "$EXT_TEMPLATE/manifest.json" "$EXT_OUT/"
  sed "s/__HIGHLIGHT_NO__/$(js_str "$HIGHLIGHT_NO")/g" \
    "$EXT_TEMPLATE/content.js" > "$EXT_OUT/content.js"
else
  log "HIGHLIGHT_NO empty — skipping highlight extension"
  rm -rf "$EXT_OUT"
fi

log "Configuration applied."
