#!/usr/bin/env bash
# Apply chronomoto.conf values to split-view config.js and Chromium extension.
# Called by setup.sh — GPL-3.0-or-later

set -euo pipefail

INSTALL_DIR="${1:?INSTALL_DIR required}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="${CONFIG_FILE:-$SCRIPT_DIR/chronomoto.conf}"

if [[ -f "$CONFIG_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$CONFIG_FILE"
fi

HIGHLIGHT_NO="${HIGHLIGHT_NO:-214}"
TOP_URL="${TOP_URL:-https://live.chronomoto.com/mx/}"
BOTTOM_URL="${BOTTOM_URL:-https://live.chronomoto.com/archive}"
ARCHIVE_TITLE="${ARCHIVE_TITLE:-ARCHIVE}"
DEFAULT_SPLIT="${DEFAULT_SPLIT:-60}"
SPLIT_CONFIG="${INSTALL_DIR}/split-view/config.js"
EXT_OUT="${SCRIPT_DIR}/extension-built"
EXT_TEMPLATE="${SCRIPT_DIR}/extension-template"

log() { echo "==> [apply-config] $*"; }

# Escape single quotes for JS strings
js_str() { printf "%s" "$1" | sed "s/'/\\\\'/g"; }

log "Writing split-view config.js"
cat > "$SPLIT_CONFIG" << EOF
// Generated by raspberry-pi/apply-config.sh — edit chronomoto.conf and re-run setup.sh
window.CHRONOMOTO_SPLIT_CONFIG = {
  topUrl: '$(js_str "$TOP_URL")',
  bottomUrl: '$(js_str "$BOTTOM_URL")',
  archiveTitle: '$(js_str "$ARCHIVE_TITLE")',
  defaultSplit: ${DEFAULT_SPLIT},
};
EOF

## Build a single extension directory (`$EXT_OUT`) that contains
## the highlight script (if configured) and any userscripts so
## Chromium can load them with a single --load-extension.
rm -rf "$EXT_OUT"
mkdir -p "$EXT_OUT"

shopt -s nullglob
all_js=()

if [[ -n "$HIGHLIGHT_NO" ]]; then
  log "Adding highlight script for rider No. ${HIGHLIGHT_NO}"
  sed "s/__HIGHLIGHT_NO__/$(js_str "$HIGHLIGHT_NO")/g" \
    "$EXT_TEMPLATE/content.js" > "$EXT_OUT/content-highlight.js"
  all_js+=("content-highlight.js")
fi

# Copy userscripts from install tree into the extension root
US_SRC_DIR="${INSTALL_DIR}/userscripts"
if [[ -d "$US_SRC_DIR" ]]; then
  js_files=("$US_SRC_DIR"/*.user.js "$US_SRC_DIR"/*.js)
  if (( ${#js_files[@]} )); then
    log "Adding ${#js_files[@]} userscript(s) to extension"
    for src in "${js_files[@]}"; do
      base=$(basename "$src")
      cp "$src" "$EXT_OUT/$base"
      all_js+=("$base")
    done
  fi
fi

if (( ${#all_js[@]} )); then
  # Build manifest.json collecting all content scripts
  js_list=""
  first=1
  for f in "${all_js[@]}"; do
    if [[ $first -eq 1 ]]; then
      js_list="\"$f\""
      first=0
    else
      js_list="$js_list, \"$f\""
    fi
  done

  cat > "$EXT_OUT/manifest.json" << EOF
{
  "manifest_version": 3,
  "name": "Chronomoto Kiosk Extension",
  "version": "1.0",
  "description": "Highlight + userscripts for Chronomoto kiosk",
  "content_scripts": [
    {
      "matches": ["*://live.chronomoto.com/*"],
      "js": [ $js_list ],
      "run_at": "document_idle",
      "all_frames": true
    }
  ],
  "host_permissions": ["*://live.chronomoto.com/*"]
}
EOF
  log "Built combined extension with ${#all_js[@]} script(s) -> $EXT_OUT"
else
  log "No highlight or userscripts found — leaving $EXT_OUT empty"
  rm -rf "$EXT_OUT"
fi

shopt -u nullglob

log "Configuration applied."
