// Generated by apply-config.sh — do not edit (edit chronomoto.conf instead)
(function () {
  'use strict';

  const DEFAULT_NO = '__HIGHLIGHT_NO__';
  const KIOSK_MODE = true;
  const STORAGE_KEY = 'cm_highlight_no';
  const POLL_MS = 700;
  const HL_BG = '#FFD600';
  const HL_FG = '#000000';
  const HL_BORDER = '3px solid #FF3300';
  const NO_COL_INDEX = 2;

  if (!DEFAULT_NO) return;

  function storageGet(key, fallback) {
    try { return localStorage.getItem(key) || fallback; }
    catch { return fallback; }
  }

  function storageSet(key, val) {
    try { localStorage.setItem(key, val); } catch {}
  }

  function setStatus() {}

  function clearHighlights() {
    document.querySelectorAll('[data-cm-hl]').forEach(el => {
      el.removeAttribute('data-cm-hl');
      ['background', 'background-color', 'color', 'outline', 'box-shadow', 'font-weight']
        .forEach(p => el.style.removeProperty(p));
    });
  }

  function highlightRow(tr) {
    const mark = el => {
      el.setAttribute('data-cm-hl', '1');
      el.style.setProperty('background', HL_BG, 'important');
      el.style.setProperty('background-color', HL_BG, 'important');
      el.style.setProperty('color', HL_FG, 'important');
      el.style.setProperty('font-weight', 'bold', 'important');
    };
    mark(tr);
    tr.style.setProperty('outline', HL_BORDER, 'important');
    tr.style.setProperty('box-shadow', '0 0 0 2px #FF3300 inset', 'important');
    tr.querySelectorAll('td, td *').forEach(mark);
  }

  function cellText(td) {
    return (td.innerText || td.textContent || '').trim();
  }

  function getDataTable() {
    const tables = document.querySelectorAll('table');
    for (const t of tables) {
      const rows = t.querySelectorAll('tr');
      if (rows.length < 5) continue;
      for (let ri = 0; ri < Math.min(rows.length, 6); ri++) {
        const cells = rows[ri].querySelectorAll('td');
        if (cells.length < 4) continue;
        const val = cellText(cells[NO_COL_INDEX]);
        if (/^\d+$/.test(val)) return t;
      }
    }
    return null;
  }

  function applyHighlight(rawTarget) {
    clearHighlights();
    const target = (rawTarget || '').trim();
    if (!target) return;

    const table = getDataTable();
    if (!table) return;

    table.querySelectorAll('tr').forEach(tr => {
      const cells = tr.querySelectorAll('td');
      if (cells.length < 4) return;
      if (!cells[NO_COL_INDEX]) return;
      if (cellText(cells[NO_COL_INDEX]) === target) highlightRow(tr);
    });

    const el = document.querySelector('tr[data-cm-hl]');
    if (el) el.scrollIntoView({ behavior: 'smooth', block: 'center' });
  }

  if (!KIOSK_MODE) {
    // Desktop-style panel omitted in kiosk builds
  }

  storageSet(STORAGE_KEY, DEFAULT_NO);

  let busy = false;
  function scheduleApply() {
    if (busy) return;
    busy = true;
    requestAnimationFrame(() => {
      applyHighlight(storageGet(STORAGE_KEY, DEFAULT_NO));
      busy = false;
    });
  }

  new MutationObserver(scheduleApply).observe(document.body, {
    childList: true, subtree: true, characterData: true,
  });
  setInterval(scheduleApply, POLL_MS);

  setTimeout(() => applyHighlight(DEFAULT_NO), 1000);
  setTimeout(() => applyHighlight(DEFAULT_NO), 2500);
})();
